# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'D2U' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for D2U

  target 'D2UTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'D2UUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'Firebase/Database'

end
