# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt/untitled/mainwindow.ui'
#
# Created: Sat Feb 10 17:43:27 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(853, 460)
		self.centralWidget = QtGui.QWidget(MainWindow)
		self.centralWidget.setObjectName("centralWidget")
		self.horizontalLayoutWidget = QtGui.QWidget(self.centralWidget)
		self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 201, 31))
		self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
		self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
		self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.label = QtGui.QLabel(self.horizontalLayoutWidget)
		self.label.setObjectName("label")
		self.horizontalLayout_2.addWidget(self.label)
		self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
		self.label_2.setObjectName("label_2")
		self.horizontalLayout_2.addWidget(self.label_2)
		self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
		self.label_3.setObjectName("label_3")
		self.horizontalLayout_2.addWidget(self.label_3)
		self.graphicsView = QtGui.QGraphicsView(self.centralWidget)
		self.graphicsView.setGeometry(QtCore.QRect(320, 0, 511, 331))
		self.graphicsView.setObjectName("graphicsView")
		self.gridLayoutWidget = QtGui.QWidget(self.centralWidget)
		self.gridLayoutWidget.setGeometry(QtCore.QRect(670, 340, 160, 51))
		self.gridLayoutWidget.setObjectName("gridLayoutWidget")
		self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
		self.gridLayout.setContentsMargins(0, 0, 0, 0)
		self.gridLayout.setObjectName("gridLayout")
		self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
		self.label_5.setObjectName("label_5")
		self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
		self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
		self.label_4.setObjectName("label_4")
		self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
		self.txtRawPitch = QtGui.QLabel(self.gridLayoutWidget)
		self.txtRawPitch.setObjectName("txtRawPitch")
		self.gridLayout.addWidget(self.txtRawPitch, 0, 1, 1, 1)
		self.txtFilteredPitch = QtGui.QLabel(self.gridLayoutWidget)
		self.txtFilteredPitch.setObjectName("txtFilteredPitch")
		self.gridLayout.addWidget(self.txtFilteredPitch, 1, 1, 1, 1)
		self.verticalLayoutWidget = QtGui.QWidget(self.centralWidget)
		self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 100, 31, 201))
		self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
		self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
		self.label_6.setObjectName("label_6")
		self.verticalLayout.addWidget(self.label_6)
		self.motorSlider = QtGui.QSlider(self.verticalLayoutWidget)
		self.motorSlider.setMinimum(-100)
		self.motorSlider.setMaximum(100)
		self.motorSlider.setSingleStep(50)
		self.motorSlider.setPageStep(50)
		self.motorSlider.setSliderPosition(0)
		self.motorSlider.setOrientation(QtCore.Qt.Vertical)
		self.motorSlider.setTickPosition(QtGui.QSlider.TicksAbove)
		self.motorSlider.setObjectName("motorSlider")
		self.verticalLayout.addWidget(self.motorSlider)
		self.driveLabel = QtGui.QLabel(self.verticalLayoutWidget)
		self.driveLabel.setAlignment(QtCore.Qt.AlignCenter)
		self.driveLabel.setObjectName("driveLabel")
		self.verticalLayout.addWidget(self.driveLabel)
		self.resetBttn = QtGui.QPushButton(self.centralWidget)
		self.resetBttn.setGeometry(QtCore.QRect(710, 400, 75, 23))
		self.resetBttn.setObjectName("resetBttn")
		self.layoutWidget = QtGui.QWidget(self.centralWidget)
		self.layoutWidget.setGeometry(QtCore.QRect(40, 40, 201, 301))
		self.layoutWidget.setObjectName("layoutWidget")
		self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.pSlider = QtGui.QSlider(self.layoutWidget)
		self.pSlider.setMaximum(100)
		self.pSlider.setSingleStep(10)
		self.pSlider.setOrientation(QtCore.Qt.Vertical)
		self.pSlider.setTickPosition(QtGui.QSlider.TicksAbove)
		self.pSlider.setObjectName("pSlider")
		self.horizontalLayout.addWidget(self.pSlider)
		self.iSlider = QtGui.QSlider(self.layoutWidget)
		self.iSlider.setSingleStep(10)
		self.iSlider.setOrientation(QtCore.Qt.Vertical)
		self.iSlider.setTickPosition(QtGui.QSlider.TicksAbove)
		self.iSlider.setObjectName("iSlider")
		self.horizontalLayout.addWidget(self.iSlider)
		self.dSlider = QtGui.QSlider(self.layoutWidget)
		self.dSlider.setSingleStep(10)
		self.dSlider.setOrientation(QtCore.Qt.Vertical)
		self.dSlider.setTickPosition(QtGui.QSlider.TicksAbove)
		self.dSlider.setObjectName("dSlider")
		self.horizontalLayout.addWidget(self.dSlider)
		self.gridLayoutWidget_2 = QtGui.QWidget(self.centralWidget)
		self.gridLayoutWidget_2.setGeometry(QtCore.QRect(270, 340, 103, 103))
		self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
		self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
		self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
		self.label_11.setObjectName("label_11")
		self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
		self.label_13 = QtGui.QLabel(self.gridLayoutWidget_2)
		self.label_13.setObjectName("label_13")
		self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
		self.minEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
		self.minEdit.setObjectName("minEdit")
		self.gridLayout_2.addWidget(self.minEdit, 1, 1, 1, 1)
		self.label_12 = QtGui.QLabel(self.gridLayoutWidget_2)
		self.label_12.setObjectName("label_12")
		self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
		self.sumEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
		self.sumEdit.setObjectName("sumEdit")
		self.gridLayout_2.addWidget(self.sumEdit, 2, 1, 1, 1)
		self.maxEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
		self.maxEdit.setObjectName("maxEdit")
		self.gridLayout_2.addWidget(self.maxEdit, 0, 1, 1, 1)
		self.setBttn = QtGui.QPushButton(self.gridLayoutWidget_2)
		self.setBttn.setObjectName("setBttn")
		self.gridLayout_2.addWidget(self.setBttn, 3, 0, 1, 2)
		self.stopButton = QtGui.QPushButton(self.centralWidget)
		self.stopButton.setGeometry(QtCore.QRect(270, 300, 31, 23))
		self.stopButton.setObjectName("stopButton")
		self.gridLayoutWidget_3 = QtGui.QWidget(self.centralWidget)
		self.gridLayoutWidget_3.setGeometry(QtCore.QRect(30, 350, 231, 74))
		self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
		self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
		self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_3.setObjectName("gridLayout_3")
		self.iEdit = QtGui.QLineEdit(self.gridLayoutWidget_3)
		self.iEdit.setAlignment(QtCore.Qt.AlignCenter)
		self.iEdit.setObjectName("iEdit")
		self.gridLayout_3.addWidget(self.iEdit, 0, 2, 1, 1)
		self.label_7 = QtGui.QLabel(self.gridLayoutWidget_3)
		self.label_7.setObjectName("label_7")
		self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
		self.iMaxEdit = QtGui.QLineEdit(self.gridLayoutWidget_3)
		self.iMaxEdit.setAlignment(QtCore.Qt.AlignCenter)
		self.iMaxEdit.setObjectName("iMaxEdit")
		self.gridLayout_3.addWidget(self.iMaxEdit, 1, 2, 1, 1)
		self.dMaxEdit = QtGui.QLineEdit(self.gridLayoutWidget_3)
		self.dMaxEdit.setAlignment(QtCore.Qt.AlignCenter)
		self.dMaxEdit.setObjectName("dMaxEdit")
		self.gridLayout_3.addWidget(self.dMaxEdit, 1, 3, 1, 1)
		self.pMaxEdit = QtGui.QLineEdit(self.gridLayoutWidget_3)
		self.pMaxEdit.setAlignment(QtCore.Qt.AlignCenter)
		self.pMaxEdit.setObjectName("pMaxEdit")
		self.gridLayout_3.addWidget(self.pMaxEdit, 1, 1, 1, 1)
		self.label_8 = QtGui.QLabel(self.gridLayoutWidget_3)
		self.label_8.setObjectName("label_8")
		self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
		self.dEdit = QtGui.QLineEdit(self.gridLayoutWidget_3)
		self.dEdit.setAlignment(QtCore.Qt.AlignCenter)
		self.dEdit.setObjectName("dEdit")
		self.gridLayout_3.addWidget(self.dEdit, 0, 3, 1, 1)
		self.pEdit = QtGui.QLineEdit(self.gridLayoutWidget_3)
		self.pEdit.setAlignment(QtCore.Qt.AlignCenter)
		self.pEdit.setObjectName("pEdit")
		self.gridLayout_3.addWidget(self.pEdit, 0, 1, 1, 1)
		self.pMinText = QtGui.QLineEdit(self.gridLayoutWidget_3)
		self.pMinText.setAlignment(QtCore.Qt.AlignCenter)
		self.pMinText.setObjectName("pMinText")
		self.gridLayout_3.addWidget(self.pMinText, 2, 1, 1, 1)
		self.iMinText = QtGui.QLineEdit(self.gridLayoutWidget_3)
		self.iMinText.setAlignment(QtCore.Qt.AlignCenter)
		self.iMinText.setObjectName("iMinText")
		self.gridLayout_3.addWidget(self.iMinText, 2, 2, 1, 1)
		self.dMinText = QtGui.QLineEdit(self.gridLayoutWidget_3)
		self.dMinText.setAlignment(QtCore.Qt.AlignCenter)
		self.dMinText.setObjectName("dMinText")
		self.gridLayout_3.addWidget(self.dMinText, 2, 3, 1, 1)
		self.label_9 = QtGui.QLabel(self.gridLayoutWidget_3)
		self.label_9.setObjectName("label_9")
		self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
		MainWindow.setCentralWidget(self.centralWidget)
		self.mainToolBar = QtGui.QToolBar(MainWindow)
		self.mainToolBar.setObjectName("mainToolBar")
		MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)
		MainWindow.setTabOrder(self.pEdit, self.iEdit)
		MainWindow.setTabOrder(self.iEdit, self.dEdit)
		MainWindow.setTabOrder(self.dEdit, self.pMaxEdit)
		MainWindow.setTabOrder(self.pMaxEdit, self.iMaxEdit)
		MainWindow.setTabOrder(self.iMaxEdit, self.dMaxEdit)
		MainWindow.setTabOrder(self.dMaxEdit, self.pMinText)
		MainWindow.setTabOrder(self.pMinText, self.iMinText)
		MainWindow.setTabOrder(self.iMinText, self.dMinText)
		MainWindow.setTabOrder(self.dMinText, self.maxEdit)
		MainWindow.setTabOrder(self.maxEdit, self.minEdit)
		MainWindow.setTabOrder(self.minEdit, self.sumEdit)
		MainWindow.setTabOrder(self.sumEdit, self.setBttn)
		MainWindow.setTabOrder(self.setBttn, self.pSlider)
		MainWindow.setTabOrder(self.pSlider, self.iSlider)
		MainWindow.setTabOrder(self.iSlider, self.dSlider)
		MainWindow.setTabOrder(self.dSlider, self.motorSlider)
		MainWindow.setTabOrder(self.motorSlider, self.stopButton)
		MainWindow.setTabOrder(self.stopButton, self.resetBttn)
		MainWindow.setTabOrder(self.resetBttn, self.graphicsView)

	def retranslateUi(self, MainWindow):
		MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
		self.label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">P</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">I</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">D</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Filtered", None, QtGui.QApplication.UnicodeUTF8))
		self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Raw Pitch", None, QtGui.QApplication.UnicodeUTF8))
		self.txtRawPitch.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
		self.txtFilteredPitch.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
		self.label_6.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">Drive</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.driveLabel.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.resetBttn.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
		self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Max", None, QtGui.QApplication.UnicodeUTF8))
		self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Sum", None, QtGui.QApplication.UnicodeUTF8))
		self.minEdit.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Min", None, QtGui.QApplication.UnicodeUTF8))
		self.sumEdit.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.maxEdit.setText(QtGui.QApplication.translate("MainWindow", "1000", None, QtGui.QApplication.UnicodeUTF8))
		self.setBttn.setText(QtGui.QApplication.translate("MainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
		self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
		self.iEdit.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
		self.iMaxEdit.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
		self.dMaxEdit.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
		self.pMaxEdit.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
		self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Max", None, QtGui.QApplication.UnicodeUTF8))
		self.dEdit.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.pEdit.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.pMinText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.iMinText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.dMinText.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
		self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Min", None, QtGui.QApplication.UnicodeUTF8))

